import type { Metadata } from "next";
import Navbar from "../components/layout/Navbar";

import "./globals.css";
import TopBarClock from "../components/layout/TopBarClock";
import Footer from "../components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={``}>
        <TopBarClock/>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
